In [1]:
import numpy as np
from BPR import BPR
from tqdm import tqdm
import pandas as pd

In [2]:
aa = np.array([[0,1,2,5],[90,10,5,1000],[9,1,3,100]])
top = np.argpartition(aa, -2)[:,-2:]
aa[np.arange(aa.shape[0])[:, None],top]

array([[   2,    5],
       [  90, 1000],
       [   9,  100]])

In [3]:

bpr = BPR()
tmp = bpr.main()

train_count: 100%|██████████| 1000/1000 [27:10<00:00,  1.63s/it]


AUC: 0.8139049847081666


In [11]:
np.argpartition(tmp[0], -10)[-10:]

array([2591, 3472, 1729,  247, 4092, 3020,  201, 1624, 1850,  217])

In [15]:
np.argsort(-tmp[1])[:10]

array([1624, 1850,  217,  247, 4092,  201, 2591, 3020, 3472,  179])

In [ ]:

first = True
for i, item_list in tqdm(enumerate(tmp), desc = "submit"):
    for j in item_list:
        tmp_df = pd.DataFrame({"user":bpr.idx2user_dict[i],"item":j}, index = [0])
        if first:
            first = False
            return_df = tmp_df
        else:
            return_df = pd.concat([return_df, tmp_df], axis = 0, sort = False)

In [13]:

return_df = return_df.sort_values(by=["user"])
return_df.to_csv("/opt/ml/output/submission.csv", index = False)

array([1776, 2581, 1624, 2213, 6754, 5196, 5469, 5440, 3754, 4630])